### ISSUE TITLE
Xreal Air 2 Pro do not work on mint (with steamvr)

### ISSUE THREAD

**Issue by konsultaner** [wheaney/breezy-desktop#10]
I tried the driver with my xreal air 2 pro and it doesn't work. I'm on linux mint 21

When I connect them, I get a second screen and the mouse starts to follow the xreal movements. So it seems it is somehow workng but not fully. I have steam with steamvr as openxr server. I also tried monado, but monado not yet supports the xreal 2 pro.

**Comment by wheaney** [comment]
If the mouse is following your movements, that's means you're in mouse mode. If you're looking for a pinned virtual display, make sure you've followed all the guidance [here](https://github.com/wheaney/breezy-desktop?tab=readme-ov-file#manual-installation), including the Usage section immediately below that, which tells you how to switch into virtual display mode.

**Comment by wheaney** [comment]
Also my driver isn't compatible with SteamVR. So you should disable my driver while attempting to use VR.

**Comment by konsultaner** [comment]
Thanks for the quick response!

> If the mouse is following your movements, that's means you're in mouse mode. If you're looking for a pinned virtual display, make sure you've followed all the guidance [here](https://github.com/wheaney/breezy-desktop?tab=readme-ov-file#manual-installation), including the Usage section immediately below that, which tells you how to switch into virtual display mode.

I tried all the modes you described and nothing worked except the mouse mode. I also quit steam vr and it still didn't work.

> Also my driver isn't compatible with SteamVR. So you should disable my driver while attempting to use VR.

I thought it would work if I use SteamVR as OpenXR server.

**Comment by wheaney** [comment]
> I thought it would work if I use SteamVR as OpenXR server.

Nope, my app is not an OpenXR server. If you installed Breezy, then you've installed a vulkan implicit layer than injects my custom shader into Vulkan games. From virtual display mode, this modifies the output of the games to track your head movements and render as a virtual display.
