### ISSUE TITLE
Is this GDPR complient?

### ISSUE THREAD

**Issue by LeifAndersen** [wheaney/breezy-desktop#14]
I notice that this sends metrics information to Google Analytics. However, I don't see anything about that in either the README or LICENSE files. This 'might' be a GDPR violation. (If nothing else _please_ post a notice about it in the readme.)

**Comment by wheaney** [comment]
Thanks for the heads-up. I implemented the Google Analytics piece a while ago and didn't think to re-investigate it when I was looking into GDPR stuff with the addition of Supporter Tier. I just investigated and it looks like GA is expecting some implementation of consent (in my case I would need to track it in my back-end), and I should probably not be sending my `user_id` unless the user is opted in. I can't turn this off immediately as my code runs on the client and requires a decky store update (for decky users anyway), but I think the following steps will be necessary:
1. For now, remove `user_id` from my analytics request
2. (In the future, maybe) Add some form of consent to get `user_id` added back in

**Comment by wheaney** [comment]
Fixed in [this commit](https://github.com/wheaney/XRLinuxDriver/commit/b338d3eb9c285b19d1a6b9719055792a2a4d3dd2).

**Comment by wheaney** [comment]
I've also added a note to the Data Privacy sections of my READMEs that the current version and earlier has that analytics integration.

**Comment by wheaney** [comment]
Supporter Tier already works the way you described. It downloads a signed license that can be verified and utilized offline. Google Analytics integration isn't tied to that (which is why I overlooked it when doing the GDPR research for Supporter Tier).

**Comment by LeifAndersen** [comment]
Ah, okay, I misread the metrics plugin, my apology. Still, it would be nice to have the option to turn them on/off. (Or maybe I just missed it.)
