### ISSUE TITLE
[FR]: Respect XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by LeifAndersen** [wheaney/breezy-desktop#17]
Right now the xreal config files seem to go directly into the user's home directory. While its not the end of the world, a nicer solution would be to have it follow the `$XDG_CONFIG_HOME` location), this way, the user can:

1. Have their config files in the place they expect config files to go, and
2. Not add an extra dot file to their home (unless that's what they wanted).

According to the spec https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html :

>  $XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

**Comment by wheaney** [comment]
I'm going to close this in favor of https://github.com/wheaney/breezy-desktop/issues/4

**Comment by LeifAndersen** [comment]
Woops, didn't see that one, thanks. :D
