### ISSUE TITLE
No errors - but screen is static. 

### ISSUE THREAD

**Issue by TutajITeraz** [wheaney/breezy-desktop#21]
Hello!
Thank you for creating and maintaining such amazing piece of software!

I've just get the Xreal Air (first model).
Nebula works on windows (but low FPS).

On linux i can set up this glasses as mirrored or duplicated screen.

I have used installation setup script - no errors
Then:
```
~/bin/xreal_driver_config -e
~/bin/xreal_driver_config -vd
```

returns no error. 
-m option is moving my mouse cursor, so i know that connection works fine.

I'm using Lenovo ThinkPad X270
Intel® HD Graphics 620 (KBL GT2)
Newest Manjaro Linux (Linux 6.6.26-1-MANJARO)
GNOME 45.5
Wayland and X11 - i have tried both. 

Please, help

**Comment by drmhck** [comment]
Exactly the same here.

- XREAL AIR Pro 2
- Ubuntu 24.04 LTS (Linux 6.8.0-31-generic)
- GNOME 46
- Wayland

**Comment by wheaney** [comment]
Hi @drmhck I believe OP here was actually trying to run this as a virtual desktop app (it was resolved in Discord). Can you describe what Breezy version you're trying to run and what setup steps you did?

**Comment by drmhck** [comment]
Latest release version. I did all steps from GNOME Setup section in README.

**Comment by wheaney** [comment]
What do you see when you launch the Breezy Desktop app?

**Comment by wheaney** [comment]
Can you send me all of the follow logs:
* everything in ~/.local/state/breezy_gnome/logs/
* ~/.xreal_driver_log

**Comment by drmhck** [comment]
Yeah, all seems to be working fine right now. Lots of thanks!
