### ISSUE TITLE
gnome-shell+air2 pro

### ISSUE THREAD

**Issue by stefanw1337** [wheaney/breezy-desktop#26]
The switch for turning the feature ON keeps turned right back off. Why?

Running gnome-shell on xfce/Linux Mint. I already have a popup from before, allowing me to extend the glasses as a 2nd monitor, but not lock it in place or zoom. And I tried all settings before trying to turn it on.

**Comment by wheaney** [comment]
Can you send me the latest log files in `~/.local/state/breezy_gnome/logs/gjs/`?

**Comment by stefanw1337** [comment]
There's no gjs folder, just "ui".

**Comment by stefanw1337** [comment]
Tried running it once more, this time I didn\t get a iu within the window, terminal running gnome/shell said this:
`(gnome-shell:4745): Clutter-WARNING **: 00:47:16.042: Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x559c83658300] is on because it needs an allocation.

(gnome-shell:4745): Clutter-WARNING **: 00:47:16.043: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x559c84a62b30] is on because it needs an allocation.

(gnome-shell:4745): Clutter-WARNING **: 00:47:16.043: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x559c84a66a50] is on because it needs an allocation.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x1200004
`

**Comment by wheaney** [comment]
So the extension just isn't running at all. When you ran the setup script, were there any errors in the output?

If not, I think we'll have to find what we're looking for in journalctl then. Try something like `journalctl --grep breezy` and see if there's anything.

**Comment by stefanw1337** [comment]
That's right, that time it didn't connect. I didn't get any errors that I noticed when running install-script.

This is what I got running:
$ journalctl --grep breezy | grep breezy (Had to actually run grep, to not get 100s of junk-lines)
```
Jun 28 16:40:53 stefanw1337-HP-EliteBook-x360-1030-G2 flatpak[14227]: user: Added remote breezydesktop-origin to
Jun 28 16:41:19 stefanw1337-HP-EliteBook-x360-1030-G2 flatpak[14227]: user: Installed app/com.xronlinux.BreezyDesktop/x86_64/master from breezydesktop-origin
Jun 28 16:41:20 stefanw1337-HP-EliteBook-x360-1030-G2 dbus-daemon[662]: [system] Activating via systemd: service name='net.reactivated.Fprint' unit='fprintd.service' requested by ':1.243' (uid=0 pid=14376 comm="sudo bin/xreal_driver_setup /tmp/breezy-gnome-oQSE" label="unconfined")
Jun 28 16:41:26 stefanw1337-HP-EliteBook-x360-1030-G2 sudo[14376]: stefanw1337 : TTY=pts/0 ; PWD=/tmp/breezy-gnome-oQSEI5203v/breezy_gnome ; USER=root ; COMMAND=bin/xreal_driver_setup /tmp/breezy-gnome-oQSEI5203v/breezy_gnome/xrealAirLinuxDriver.tar.gz
Jun 28 21:47:52 stefanw1337-HP-EliteBook-x360-1030-G2 kernel: [   2524]  1000  2524   363014     1823   651264     9377             0 breezydesktop
Jun 28 21:48:01 stefanw1337-HP-EliteBook-x360-1030-G2 kernel: [   2524]  1000  2524   363014     1823   651264     9377             0 breezydesktop
Jun 28 21:48:01 stefanw1337-HP-EliteBook-x360-1030-G2 kernel: [   2524]  1000  2524   363014     1823   651264     9377             0 breezydesktop
Jun 28 21:49:06 stefanw1337-HP-EliteBook-x360-1030-G2 kernel: [   2524]  1000  2524   363014      805   651264    10395             0 breezydesktop
Jun 28 21:49:31 stefanw1337-HP-EliteBook-x360-1030-G2 kernel: [   2524]  1000  2524   363014      804   651264    10396             0 breezydesktop
Jun 28 21:49:32 stefanw1337-HP-EliteBook-x360-1030-G2 kernel: [   2524]  1000  2524   363014      804   651264    10396             0 breezydesktop
Jun 28 21:52:39 stefanw1337-HP-EliteBook-x360-1030-G2 kernel: [   2524]  1000  2524   363014      803   651264    10397             0 breezydesktop
Jun 28 21:52:39 stefanw1337-HP-EliteBook-x360-1030-G2 kernel: [   2524]  1000  2524   363014      803   651264    10397             0 breezydesktop
Jun 28 21:52:39 stefanw1337-HP-EliteBook-x360-1030-G2 kernel: [   2524]  1000  2524   363014      803   651264    10397             0 breezydesktop
Jun 28 21:52:39 stefanw1337-HP-EliteBook-x360-1030-G2 kernel: [   2524]  1000  2524   363014      803   651264    10397             0 breezydesktop
Jun 29 00:40:41 stefanw1337-HP-EliteBook-x360-1030-G2 dbus-daemon[662]: [system] Activating via systemd: service name='net.reactivated.Fprint' unit='fprintd.service' requested by ':1.141' (uid=0 pid=4587 comm="sudo find / -type d -name breezy_gnome " label="unconfined")
Jun 29 00:40:49 stefanw1337-HP-EliteBook-x360-1030-G2 sudo[4587]: stefanw1337 : TTY=pts/0 ; PWD=/ ; USER=root ; COMMAND=/usr/bin/find / -type d -name breezy_gnome
```

**Comment by wheaney** [comment]
I just noticed this issue dropped off my radar. Do you mind trying rerunning the setup to get the latest? There have been a bunch of changes since this, some that address instability.

Also, can you clarify since you mention you're using xfce, are you running `gnome-shell` nested?

**Comment by wheaney** [comment]
@stefanw1337 Gonna close this out since it's been a while and a lot of stability fixes have been made. If you install the latest and still run into this, feel free to reopen.
