### ISSUE TITLE
Move windows to virtual screens

### ISSUE THREAD

**Issue by hodasemi** [wheaney/breezy-desktop#32]
I noticed that moving windows to virtual screen does also not work with the extension enabled. I'm using the AUR package.

My setup:

* Gnome 46
* Wayland
* Viture One

**Comment by wheaney** [comment]
Can you expand on this? Is it possible that GNOME is placing your monitor in an unexpected orientation? It's possible to drag the display so it sits above, left, bottom, or right of the native display.

**Comment by hodasemi** [comment]
Sorry, the issue description is kinda wonky.

### Expected behaviour
This also work 100% of the time when in normal desktop mode, without the extension enabled, but also the glasses connected.

* go in overview mode (super key or top left corner)
* drag a window into another screen (no matter if physical or virtual)
* drop it there
* the window is then moved to another screen

### Occuring behaviour
This occurs when the extension is enabled and the glasses are connected

* go in overview mode (super key or top left corner)
* drag a window into another screen (no matter if physical or virtual)
* drop it there
* the window is dropped back to the source screen, nothing is moved, no further screens are created if necessary

**Comment by wheaney** [comment]
Oh, I've seen this too but never attributed it to my plugin. Makes sense that it might be causing this, though, as it's putting an overlay over the top of the display, that must be absorbing the drag-n-drop events somehow.

**Comment by zot** [comment]
I have the same problem. I saw one message for Zorin mentioning that Gnome Tweak "mouse click emulation" can interfere with dragging windows to other work spaces so I wonder if maybe the problem has to do with how Breezy handles mouse events.

Just a guess but perhaps this code is violating an expectation?
(sorry I don't have time today to comment out this extension code and test this out myself)

https://github.com/wheaney/breezy-desktop/blob/04e8bf2a6ec3efd6ab1a9dffece09a1bd33eec9d/gnome/src/cursormanager.js#L258-L261

**Comment by wheaney** [comment]
v1.1.x fixes this. I'll have this out to AUR soon, in the meantime, those running from the manual setup process can just rerun setup to get the latest version.
