### ISSUE TITLE
does it work with kde? 

### ISSUE THREAD

**Issue by manoflinux** [wheaney/breezy-desktop#38]
I have the gnome libraries loaded and run gnome apps in kde all the time, so would this work? 
don't have problem getting a life time license if it works with kde at least mostly.

**Comment by wheaney** [comment]
Check the "other distros" setup section. That outlines the only options we have until I build native KWin support.

**Comment by manoflinux** [comment]
> Check the "other distros" setup section. That outlines the only options we have until I build native KWin support.

thanks!

**Comment by wheaney** [comment]
Sorry, I was on mobile and going from memory, but it would actually be the [non-gnome setup](https://github.com/wheaney/breezy-desktop#non-gnome-setup) instructions in this case.

**Comment by manoflinux** [comment]
even better thanks!
