### ISSUE TITLE
Can't open Breezy Desktop on Arch (with gnome 46)

### ISSUE THREAD

**Issue by rogershijin** [wheaney/breezy-desktop#39]
Screen extension works great and the Viture device is detected in displays and the displays can be rearranged. I'm interested in pinning virtual windows in space and ultrawide etc. though, which seems like it would require the Breezy Desktop app, but I'm having trouble opening the app. 

Pressing Super to open the search bar and typing "Breezy Desktop" shows and selects the penguin with sunglasses icon, but pressing Enter just causes my cursor to turn into a loading wheel and then turn back to normal after a while.

Opening a terminal and running

```
gnome-terminal -- breezydesktop
```

Produces the error

```
# Couldn't connect to accessibility bus: Failed to connect to socket /run/user/1000/at-spi/bus_0: Connection refused
```

Btw I installed via AUR with yay and on first attempt I got an error saying `no module named yaml` so I opened a conda environment with `pyyaml` and reran the install command and it worked. 

Thanks!

**Comment by rogershijin** [comment]
If there's a config file I can edit to get the same effect as using the app that would actually be even better for my habits than getting the app working.

**Comment by wheaney** [comment]
I'm a bit surprised about the AUR install, [the current PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=xr-driver-breezy-gnome-git) depends on `python-yaml`.

Regarding the UI, can you see if there are any logs? `~/.local/state/breezy_gnome/logs/ui/[log]`
Can you also try tailing journalctl using `journalctl -f` and then attempting to launch the UI, see if anything relevant shows up in that output?

You can enable widescreen mode by updating the gsettings value: `dconf /com/xronlinux/BreezyDesktop/widescreen-mode true`

**Comment by rogershijin** [comment]
Thanks for the help! There's no `breezy_gnome` directory under `~/.local/state` unfortunately. `journalctl -f` produes

```
 Aug 02 02:45:16 xps gnome-terminal-[79374]: gnome-terminal-server has no capability of surrounding-text feature
Aug 02 02:45:16 xps systemd[1939]: vte-spawn-8e465a86-df81-4ae0-bace-3318536e7893.scope: Couldn't move process 80554 to requested cgroup '/user.slice/user-1000.slice/user@1000.service/app.slice/app-org.gnome.Terminal.slice/vte-spawn-8e465a86-df81-4ae0-bace-3318536e7893.scope': No such process
Aug 02 02:45:16 xps systemd[1939]: vte-spawn-8e465a86-df81-4ae0-bace-3318536e7893.scope: Failed to add PIDs to scope's control group: No such process
Aug 02 02:45:16 xps systemd[1939]: vte-spawn-8e465a86-df81-4ae0-bace-3318536e7893.scope: Failed with result 'resources'.
Aug 02 02:45:16 xps systemd[1939]: Failed to start VTE child process 80554 launched by gnome-terminal-server process 79374.
```

I ran
```
dconf write /com/xronlinux/BreezyDesktop/widescreen-mode true
```
but widescreen mode didn't turn on. Then I tried restarting but it was still 16:9.

**Comment by rogershijin** [comment]
I then ran `pacman -Sy python-gobject` and I got errors pointing to the `pygobject` within my conda environment. I then uninstalled breezy and resinstalled and now I'm getting this error

```
Aug 02 03:08:57 xps com.xronlinux.BreezyDesktop.desktop[18788]: Traceback (most recent call last):
Aug 02 03:08:57 xps com.xronlinux.BreezyDesktop.desktop[18788]:   File "/usr/bin/breezydesktop", line 41, in <module>
Aug 02 03:08:57 xps com.xronlinux.BreezyDesktop.desktop[18788]:     from gi.repository import Gio
Aug 02 03:08:57 xps com.xronlinux.BreezyDesktop.desktop[18788]: ModuleNotFoundError: No module named 'gi.repository'
Aug 02 03:08:58 xps systemd[1941]: app-gnome-com.xronlinux.BreezyDesktop-18788.scope: Couldn't move process 18788 to requested cgroup '/user.slice/user-1000.slice/user@1000.service/app.slice/app-gnome-com.xronlinux.BreezyDesktop-18788.scope': No such process
Aug 02 03:08:58 xps systemd[1941]: app-gnome-com.xronlinux.BreezyDesktop-18788.scope: Failed to add PIDs to scope's control group: No such process
Aug 02 03:08:58 xps systemd[1941]: app-gnome-com.xronlinux.BreezyDesktop-18788.scope: Failed with result 'resources'.
Aug 02 03:08:58 xps systemd[1941]: Failed to start Application launched by gnome-shell.
```

**Comment by wheaney** [comment]
I'm thinking I probably need to add a couple more depends:
* `python-gobject`
* `libgirepository`
* `glib2-git` (it's not accessible from pacman, but `glib` hasn't received an update since 2021...)

And maybe the Adw theme just to be sure? I didn't port this to AUR and my flatpak install was taking care of all this for me.
* `adw-gtk-theme`

**Comment by wheaney** [comment]
Can you try manually installing `gtk4` to see if it resolves these? I'm kind of surprised it's even necessary on gnome 46.

**Comment by rogershijin** [comment]
This didn't work but I can't even run the `hello.py` script [here in the PyGObject docs](https://pygobject.gnome.org/getting_started.html) so it's definitely some problem on my end.

**Comment by rogershijin** [comment]
I deleted `electron25` which was blocking some upgrades, then ran `pacman -Syu` and the desktop app started working. Thanks for all the help!

**Comment by wheaney** [comment]
Closing this out.
