### ISSUE TITLE
Update setup to use proper config/data home directories

### ISSUE THREAD

**Issue by wheaney** [wheaney/breezy-desktop#4]
Per the [Vulkan Linux Layer Discovery](https://github.com/KhronosGroup/Vulkan-Loader/blob/main/docs/LoaderLayerInterface.md#linux-layer-discovery) documentation, before the setup script copies our vkBasalt config and lib files to ~/.config and ~/.local, we should be checking whether `$XDG_CONFIG_HOME` or `$XDG_DATA_HOME` environment variables are set and use them if they are.

**Comment by wheaney** [comment]
We should also be moving the driver's bin and config files to their proper directories. Keep in mind you'd need to update the setup scripts to copy the existing config file if the user already has one.

**Comment by wheaney** [comment]
Also note that the setup scripts call uninstall for the previous version already, so if you just update setup to do install properly going forward, you don't need to clean up the old bin files. Only the config file needs special treatment to be preserved.

**Comment by wheaney** [comment]
We should also update the README docs to reference new bin and config file locations.

**Comment by pravic** [comment]
`~/.xreal_driver_log` should be moved somewhere better as well.

**Comment by wheaney** [comment]
Just a note: all my recommendations above are based on eventually moving to a user-systemd service (instead of system/root like it is now).

Additional recommendations from a convo on the Discord:
> If stuff is reading and writing to the user-directory then the systemd unit should probably be a user-unit in ${XDG_CONFIG_HOME}/systemd/user too.
> Likewise IPC and lock bits would go into ${XDG_RUNTIME_DIR}/xr_driver
> Rather than ~/.local/share/xr_driver/logs logs are considered state so would go to ${XDG_STATE_HOME}/xr_driver/logs

We should also move the license file currently located at `/var/lib/xr_driver/device_license`.

**Comment by wheaney** [comment]
I plan to tackle this soon. Here's the current plan, slightly modified from the last, also incorporating the latest comments.

| File type | XDG directory | Fallback | Current location | 
| ------------- | ------------- | ------------- | ------------- |
| Logs and license | **$XDG_STATE_HOME/xr_driver/(logs/*\|device_license)** | ~/.local/state/xr_driver/(logs/*\|device_license) | ~/.xreal_driver_log /var/lib/xr_driver/device_license  |
| Driver binary and scripts | **$XDG_BIN_HOME/xr_driver(_setup\|_uninstall\|_cli)** | ~/.local/bin/xr_driver(_setup\|_uninstall\|_cli) | ~/bin/xrealAirLinuxDriver ~/bin/xreal_driver_(config\|uninstall) |
| Driver config | **$XDG_CONFIG_HOME/xr_driver/config.ini** | ~/.config/xr_driver/config.ini |  ~/.xreal_driver_config |
| systemd unit | **$XDG_CONFIG_HOME/systemd/user/xr-driver.service** | ~/.config/systemd/user/xr-driver.service | /etc/systemd/system/xreal-air-driver.service |
| Lock file | **$XDG_RUNTIME_DIR/xr_driver/lock.pid** | /tmp/xr_driver/lock.pid | ~/.xreal_driver_lock |
| IPC | n/a | n/a | /dev/shm/xr_driver_(state\|control) - unchanged, uses shared memory location |

**Comment by wheaney** [comment]
XRLinuxDriver portion almost complete in https://github.com/wheaney/XRLinuxDriver/compare/xdg_reorg

**Comment by wheaney** [comment]
This is mostly done, it's incorporated all the Breezy Vulkan build, setup, uninstall. Breezy GNOME and decky plugin still need updates, mainly via changes to the shared [XRDriverIPC](https://github.com/wheaney/PyXRLinuxDriverIPC) module.

**Comment by wheaney** [comment]
I've pushed updates to Breezy GNOME and the decky plugin that pull in all the latest XDG reorg changes. The only thing that's left is updated the driver and breezy PKGBUILD files so AUR can build off these changes.

**Comment by wheaney** [comment]
AUR has been updated to accommodate the XDG changes. Finally closing this!
