### ISSUE TITLE
Choppy experience with XReal Air 2 Pro in widescreen

### ISSUE THREAD

**Issue by wenningerk** [wheaney/breezy-desktop#41]
I'm running Fedora 40 on Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz which of course isn't an actual dream machine.
And haven't yet checked in how far the GPU in the package is really used.
Non widescreen mode is definitely a lot smoother while I have 60Hz at FHD and 90Hz at Widescreen. Guessing that points definitely to a performance issue.
Of course getting smoother rendering would be desirable but I guess another viable way to get a useful environment could be introduction of a certain threshold below which a movement wouldn't lead to re-rendering. Like hold your head still if you want to read some small text. Haven't checked if there are controls for that under the hood already.
Did you already experiment with such an approach?

Regards,
Klaus

**Comment by wheaney** [comment]
90Hz in widescreen, but 60 otherwise? I would suggest turning off the automatic refresh rate advanced setting and manually setting the refresh rate to 60. But this might be something you just need to tolerate with your hardware, since widescreen is pushing more pixels and demands more from the hardware.

**Comment by wenningerk** [comment]
Tried that already of course but I have just 90Hz available in Widescreen and 60Hz in FHD so that I can't change anything manually. Any tips maybe how I can achieve that it just tries to render every other frame for instance instead of going for the 90Hz and ending up with something uneven and choppy?
What about the movement threshold idea?
I'm not really getting it anyway. I would suppose you're switching it into 3d mode (double-wide display with SBS data) in both cases - right? Or is FHD mode in Breezy-Desktop not 3d - didn't look that closely? Have to check again how that behaves without Breezy-Desktop interference when I switch manually between non 3D and SBS mode.

**Comment by wheaney** [comment]
I'm only using SBS mode for widescreen because gnome will recognize it as a 3840x1080 screen.

Are you saying you don't have the option to change refresh rate when in widescreen? But it's higher than standard 1080p?

**Comment by wenningerk** [comment]
Strange but yes. Haven't tried playing with approaches to enforce anything yet.
Not using SBS in non widescreen mode means that you can't define the position of the screen in space - right?
Any plans to change that? Is it intentional or just convenience as one doesn't have to fiddle with proportions and stuff?
At the moment you can use the distance as well as some kind of IPD adjustment. So this might be nice to have in non widescreen mode as well.

**Comment by wenningerk** [comment]
Have to revise that. Refresh rates offered by gnome are very unpredictable. Seems to depend on history and if switch to SBS has been triggered manually or by breezy-desktop. All very strange.

**Comment by martijndevrieze** [comment]
5.15.167-1-MANJARO
with Gnome

Have to agree, when switching out of wide-screen mode I have the option of switching refresh rate from 120 to 90 to 60. They do NOT however seem to take effect. 
When in wide screen mode I am stuk on 90 and the screen, when I move my head is indeed choppy. 
It is not a disaster, however it is noticably tiring on the eyes.

**Comment by wheaney** [comment]
GNOME manages what refresh rate options are available, unfortunately, so if you're seeing inconsistencies there, my extension can't do anything to help that. I would recommend trying 60Hz if you're experiencing choppiness at higher refresh rates. Also v1.1 may offer some improved performance, so be sure to rerun the setup occasionally to get the latest version.
