### ISSUE TITLE
[Request] KWin Effect port contribution 

### ISSUE THREAD

**Issue by mario-aleo** [wheaney/breezy-desktop#72]
I've read that you'll port to Kwin Effect to support KDE Plasma and I'm actually interested and would like to know if there's a branch or repository that you've done any work on it and if you accept any contribution 🙂

**Comment by wheaney** [comment]
I'm already tracking this here: https://github.com/wheaney/breezy-desktop/issues/36

I would love to receive contributions if you know anything about KWin Effects.
